CC=gcc
CFlags=-Wall
OBJ=runge_kutta.c plot_poblaciones.py poblaciones_x0_y0.dat
arg1=30.0 #es el x0
arg2=20 #es el y0

all:poblaciones_30_20.pdf poblaciones_29_20.pdf poblaciones_28_20.pdf poblaciones_27_20.pdf poblaciones_26_20.pdf poblaciones_25_20.pdf poblaciones_24_20.pdf poblaciones_23_20.pdf poblaciones_22_20.pdf poblaciones_21_20.pdf poblaciones_20_20.pdf poblaciones_19_20.pdf poblaciones_18_20.pdf poblaciones_17_20.pdf poblaciones_16_20.pdf poblaciones_15_20.pdf poblaciones_14_20.pdf poblaciones_13_20.pdf poblaciones_12_20.pdf poblaciones_11_20.pdf poblaciones_10_20.pdf poblaciones_9_20.pdf poblaciones_8_20.pdf poblaciones_7_20.pdf poblaciones_6_20.pdf poblaciones_5_20.pdf poblaciones_4_20.pdf poblaciones_3_20.pdf poblaciones_2_20.pdf poblaciones_1_20.pdf

poblaciones_30_20.pdf: poblaciones_30_20.dat
	python plot_poblaciones.py poblaciones_30_20.dat
poblaciones_30_20.dat: a.out
	./a.out 30 $(arg2)

poblaciones_29_20.pdf: poblaciones_29_20.dat
	python plot_poblaciones.py poblaciones_29_20.dat
poblaciones_29_20.dat: a.out
	./a.out 29 $(arg2)

poblaciones_28_20.pdf: poblaciones_28_20.dat
	python plot_poblaciones.py poblaciones_28_20.dat
poblaciones_28_20.dat: a.out
	./a.out 28 $(arg2)

poblaciones_27_20.pdf: poblaciones_27_20.dat
	python plot_poblaciones.py poblaciones_27_20.dat
poblaciones_27_20.dat: a.out
	./a.out 27 $(arg2)

poblaciones_26_20.pdf: poblaciones_26_20.dat
	python plot_poblaciones.py poblaciones_26_20.dat
poblaciones_26_20.dat: a.out
	./a.out 26 $(arg2)

poblaciones_25_20.pdf: poblaciones_25_20.dat
	python plot_poblaciones.py poblaciones_25_20.dat
poblaciones_25_20.dat: a.out
	./a.out 25 $(arg2)

poblaciones_24_20.pdf: poblaciones_24_20.dat
	python plot_poblaciones.py poblaciones_24_20.dat
poblaciones_24_20.dat: a.out
	./a.out 24 $(arg2)

poblaciones_24_20.pdf: poblaciones_24_20.dat
	python plot_poblaciones.py poblaciones_24_20.dat
poblaciones_24_20.dat: a.out
	./a.out 24 $(arg2)

poblaciones_23_20.pdf: poblaciones_23_20.dat
	python plot_poblaciones.py poblaciones_23_20.dat
poblaciones_23_20.dat: a.out
	./a.out 23 $(arg2)

poblaciones_22_20.pdf: poblaciones_22_20.dat
	python plot_poblaciones.py poblaciones_22_20.dat
poblaciones_22_20.dat: a.out
	./a.out 22 $(arg2)

poblaciones_21_20.pdf: poblaciones_21_20.dat
	python plot_poblaciones.py poblaciones_21_20.dat
poblaciones_21_20.dat: a.out
	./a.out 21 $(arg2)

poblaciones_20_20.pdf: poblaciones_20_20.dat
	python plot_poblaciones.py poblaciones_20_20.dat
poblaciones_20_20.dat: a.out
	./a.out 20 $(arg2)

poblaciones_19_20.pdf: poblaciones_19_20.dat
	python plot_poblaciones.py poblaciones_19_20.dat
poblaciones_19_20.dat: a.out
	./a.out 19 $(arg2)

poblaciones_18_20.pdf: poblaciones_18_20.dat
	python plot_poblaciones.py poblaciones_18_20.dat
poblaciones_18_20.dat: a.out
	./a.out 18 $(arg2)

poblaciones_17_20.pdf: poblaciones_17_20.dat
	python plot_poblaciones.py poblaciones_17_20.dat
poblaciones_17_20.dat: a.out
	./a.out 17 $(arg2)

poblaciones_16_20.pdf: poblaciones_16_20.dat
	python plot_poblaciones.py poblaciones_16_20.dat
poblaciones_16_20.dat: a.out
	./a.out 16 $(arg2)

poblaciones_15_20.pdf: poblaciones_15_20.dat
	python plot_poblaciones.py poblaciones_15_20.dat
poblaciones_15_20.dat: a.out
	./a.out 15 $(arg2)

poblaciones_14_20.pdf: poblaciones_14_20.dat
	python plot_poblaciones.py poblaciones_14_20.dat
poblaciones_14_20.dat: a.out
	./a.out 14 $(arg2)

poblaciones_13_20.pdf: poblaciones_13_20.dat
	python plot_poblaciones.py poblaciones_13_20.dat
poblaciones_13_20.dat: a.out
	./a.out 13 $(arg2)

poblaciones_12_20.pdf: poblaciones_12_20.dat
	python plot_poblaciones.py poblaciones_12_20.dat
poblaciones_12_20.dat: a.out
	./a.out 12 $(arg2)

poblaciones_11_20.pdf: poblaciones_11_20.dat
	python plot_poblaciones.py poblaciones_11_20.dat
poblaciones_11_20.dat: a.out
	./a.out 11 $(arg2)

poblaciones_10_20.pdf: poblaciones_10_20.dat
	python plot_poblaciones.py poblaciones_10_20.dat
poblaciones_10_20.dat: a.out
	./a.out 10 $(arg2)

poblaciones_9_20.pdf: poblaciones_9_20.dat
	python plot_poblaciones.py poblaciones_9_20.dat
poblaciones_9_20.dat: a.out
	./a.out 9 $(arg2)

poblaciones_8_20.pdf: poblaciones_8_20.dat
	python plot_poblaciones.py poblaciones_8_20.dat
poblaciones_8_20.dat: a.out
	./a.out 8 $(arg2)
    
poblaciones_7_20.pdf: poblaciones_7_20.dat
	python plot_poblaciones.py poblaciones_7_20.dat
poblaciones_7_20.dat: a.out
	./a.out 7 $(arg2)

poblaciones_6_20.pdf: poblaciones_6_20.dat
	python plot_poblaciones.py poblaciones_6_20.dat
poblaciones_6_20.dat: a.out
	./a.out 6 $(arg2)

poblaciones_5_20.pdf: poblaciones_5_20.dat
	python plot_poblaciones.py poblaciones_5_20.dat
poblaciones_5_20.dat: a.out
	./a.out 5 $(arg2)

poblaciones_4_20.pdf: poblaciones_4_20.dat
	python plot_poblaciones.py poblaciones_4_20.dat
poblaciones_4_20.dat: a.out
	./a.out 4 $(arg2)

poblaciones_3_20.pdf: poblaciones_3_20.dat
	python plot_poblaciones.py poblaciones_3_20.dat
poblaciones_3_20.dat: a.out
	./a.out 3 $(arg2)

poblaciones_2_20.pdf: poblaciones_2_20.dat
	python plot_poblaciones.py poblaciones_2_20.dat
poblaciones_2_20.dat: a.out
	./a.out 2 $(arg2)

poblaciones_1_20.pdf: poblaciones_1_20.dat
	python plot_poblaciones.py poblaciones_1_20.dat
poblaciones_1_20.dat: a.out
	./a.out 1 $(arg2)




a.out: runge_kutta.c
	cc runge_kutta.c -lm -w




